spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://34.133.175.162:3306/CAMO?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 1031
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

mybatis:
  mapper-locations: classpath:/mappers/*.xml

server:
  port: 8888