spring:
  datasource:
    url: jdbc:mysql://34.64.47.242:3306/CAMO_DB?serverTimezone=UTC
    username: root
    password: 9490
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  port : 9999

#  jpa:
#    hibernate:
#      ddl-auto: create #자동으로 테이블 생성
#    properties:
#      hibernate:
#        format_sql: true